<?php

use Drupal\post\Post;
use Drupal\library\Library;

function post_theme()
{
    return [
        'post.index' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.index'
        ],
    ];
}

function post_preprocess( &$variables, $hook )
{
    debug_log("post_preprocess($hook) begins");
    if ( post::isPostPage() ) {
        $variables['#attached']['library'][] = 'post/default';
    }
}
