<?php

use Drupal\post\Post;
use Drupal\library\Library;


define('DIR_POST', 'modules/post');
define('DIR_POST_TEMPLATES', 'modules/post/templates');
define('URL_POST', '/modules/post');
define('URL_POST_TEMPLATES', '/modules/post/templates');
define('DIR_POST_DATA', 'public://post/');

function post_theme()
{
    return [
        'post.layout' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.layout'
        ],
    ];

}

function post_preprocess( &$variables, $hook )
{

    // debug_log("post_preprocess($hook) begins");
    $variables['url_site'] = Library::getSiteUrl();
    $variables['url_post_templates'] = URL_POST_TEMPLATES;
    $variables['dir_post'] = DIR_POST;
    $variables['dir_post_templates'] = DIR_POST_TEMPLATES;
    $variables['dir_post_elements'] = DIR_POST_TEMPLATES . "/elements";
    $variables['dir_post_widgets'] = DIR_POST_TEMPLATES . "/widgets";
    $variables['url_post_widgets'] = URL_POST_TEMPLATES . "/widgets";
    $variables['global_config'] = Post::getGlobalConfig();
    $variables['error'] = Library::getError();

    //di('post.module');
    /*
    Library::parseErrorMessage($variables, "modules/post/templates/elements/error.html.twig");
    Library::parseErrorMessage($variables, 'modules/post/templates/error.html.twig');
    */

    if ( post::isPostPage() ) {
        $variables['#attached']['library'][] = 'post/default';
    }
}


