<?php

use Drupal\post\Post;
use Drupal\library\Library;


define('DIR_POST', 'modules/post');
define('DIR_POST_TEMPLATES', 'modules/post/templates');
define('URL_POST', '/modules/post');
define('URL_POST_TEMPLATES', '/modules/post/templates');

function post_theme()
{
    return [
        'post.layout' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.layout'
        ],
        /*
        'post.index' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.index'
        ],
        'post.list' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.list'
        ],
        'post.edit' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.edit'
        ],
        'post.view' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.view'
        ],
        'post.config' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.config'
        ],
        'post.search' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.search'
        ],
        'post.admin' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.admin'
        ],
        'post.error' => [
            'variables' => [ 'data' => null ],
            'template' => 'post.error'
        ],
        */
    ];

}

function post_preprocess( &$variables, $hook )
{

    // debug_log("post_preprocess($hook) begins");
    $variables['url_site'] = Library::getSiteUrl();
    $variables['url_post_templates'] = URL_POST_TEMPLATES;
    $variables['dir_post'] = DIR_POST;
    $variables['dir_post_templates'] = DIR_POST_TEMPLATES;
    $variables['global_config'] = Post::getGlobalConfig();
    $variables['error'] = Library::getError();

    Library::parseErrorMessage($variables, "modules/post/templates/elements/error.html.twig");
    Library::parseErrorMessage($variables, 'modules/post/templates/error.html.twig');

    if ( post::isPostPage() ) {
        $variables['#attached']['library'][] = 'post/default';
    }
}


